name: Dialed-In-Backend-CD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch should be deployed?"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dialed-In-Backend-CD

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Create empty .env
        run: touch .env

      - name: Determine IMAGE_TAG
        run: |
          if [ ! -z "${{ github.event.release.tag_name }}" ]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            SHA=$(git rev-parse --short HEAD)
            echo "IMAGE_TAG=$SHA" >> $GITHUB_ENV
          fi

      # Build the lowercase repo name
      - name: Compute lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/backend" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -f Dockerfile \
            -t ${IMAGE_NAME}:${IMAGE_TAG} \
            -t ${IMAGE_NAME}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${IMAGE_NAME}:latest

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Add known host
        run: ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Production
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
        run: make prod/deploy
