name: Dialed-In-Backend-CD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch should be deployed?"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dialed-In-Backend-CD

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      # Create a dummy .env so Makefile doesnâ€™t choke
      - name: Create empty .env
        run: touch .env

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Production
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
        run: make prod/deploy
